---
# Patching of test machines
- hosts: ubuntu
  become: true

  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes 
      autoremove: yes
      autoclean: yes
  - name: upgrade all packages
    apt:
      name: "*"
      state: latest
  - name: Update all packages to the latest version
    apt:
      upgrade: dist
